### ISSUE TITLE
Generate files have identical names

### ISSUE THREAD

**Issue by joswarmer** [dslmeinte/mps-open-source#2]
The names of the generated Excel files in the _usages_ and _versions_ directories are indentical. Excel refuses to open two files with the same name,  this is quite cumbersome.
I propose to generate different filenames like e.g. _version-modelname.csv_ and _usage-modelname.csv_.

**Comment by dslmeinte** [comment]
Versions and usage analyses are generated for a whole MPS project at once, so "model name" would not make sense right now - later on, when these things are more parametrised they would obviously do.

But the name for the CSV-files are parametrised through `languageVersions.reportPath` and `usageAnalysisPath`, resp.

Would that work?

**Comment by joswarmer** [comment]
Excel only looks at the simple file name, so I still cannot open two of those files at the same time.

**Comment by dslmeinte** [comment]
But if you give them distinct names in the JSON config?

**Comment by joswarmer** [comment]
You are right, will close this issue.
